### ISSUE TITLE
Is there a roadmap for supportting ceemd?

### ISSUE THREAD

**Issue by CodingPapi** [laszukdawid/PyEMD#111]
Hi, is there any plan for adding ceemd support? Thanks

**Comment by laszukdawid** [comment]
Hey, to be honest, I don't recall what CEEMD does. Any chance you could remind me? Most queries gets me to CEEMDAN.

If I recall correctly, I used to know ~5 years ago and then it was conscious decision not to include it because... reasons that I don't recall. I'm guessing that CEEMD can be already done with EEMD and specific parameters.

**Comment by CodingPapi** [comment]
Fine, Thanks for this great project

**Comment by laszukdawid** [comment]
Guess there's some misunderstanding here. There isn't a roadmap for CEEMD but I'm not opposed to it. Just honestly can't tell what it is and need some references. Even in case of "unnecessary" we might provide a tutorial/documentation on how to do it.

**Comment by CodingPapi** [comment]
CEEMD is the method of Torres et al 2011.

**Comment by laszukdawid** [comment]
Right, then that's already implemented and ready to use :)
https://pyemd.readthedocs.io/en/latest/ceemdan.html
