### ISSUE TITLE
CEEMDAN OR ICEEMDAN?

### ISSUE THREAD

**Issue by Bressanone99** [laszukdawid/PyEMD#123]
Hello, I would like to know whether the 'CEEMDAN()' provided in pyEMD is actually the **ICEEMDAN** proposed by Colominas2014？ Because I found a gap in the number of IMFs obtained between using CEEMDAN  in pyEMD and in MATLAB for the same signal data , which is closer to the result obtained by the ICEEMDAN  in MATLAB.
If the answer is yes, I wonder if I want to use pyEMD to call CEEMDAN and ICEEMDAN at the same time, and make a comparison between them, is it possible?How should the relevant parameters be set?
My English is so poor, and I hope I have expressed myself clearly. sorry to bother! I'll be grateful to receive your answer if it is convenient! Thanks a lot!

**Comment by laszukdawid** [comment]
Hi, sorry for late reply. Unfortunately, I don't know what *ICEEMDAN* in Matlab is. I was hoping that some other users could contribute here by pointing the difference.

**Comment by ctanny** [comment]
I believe the issue is that CEEMDAN in this package sometimes gives variable numbers of IMFs, or spurious IMFs. ICEEMDAN corrects this issue. I have come across this problem a number of times. But I could be wrong. Please see the following paper:
G. Colominas, Marcelo A. and Schlotthauera and M. E. Tor-
res, “Improved complete ensemble EMD: A suitable tool for
biomedical signal processing,” Biomed. Signal. Process. Con-
trol, vol. 14, pp. 19–29, Nov. 2014
Can be found here:
https://www.academia.edu/16712642/Improved_complete_ensemble_EMD_A_suitable_tool_for_biomedical_signal_processing?auto=download

**Comment by qdl16** [comment]
> 您好，我想知道pyEMD中提供的“CEEMDAN（）”是否真的是Colominas2014提出的**ICEEMDAN**？ 因为我发现在pyEMD和MATLAB中使用CEEMDAN获得的IMF数量存在差距，这更接近ICEEMDAN在MATLAB中获得的结果。如果答案是肯定的，我想知道是否要使用 pyEMD 同时调用 CEEMDAN 和 ICEEMDAN，并在它们之间进行比较，可以吗？相关参数应该如何设置？我的英语太差了，我希望我已经清楚地表达了自己。对不起，打扰了！如果方便，我将不胜感激！多谢！

Hello, have you solved this problem? How can I use CEEMDAN in PyEMD to simultaneously perform ICEEMDAN decomposition and CEEMDAN decomposition?
