### ISSUE TITLE
How to do EEMD or CEEMDAN on multi-variate time series data with a lagging window?

### ISSUE THREAD

**Issue by Waterkin** [laszukdawid/PyEMD#126]
I have learned from the doc that PyEMD needs input that is 1-D numpy array.
However, for multi-variate time series data with a lagging window, the data becomes 3-D (batch, window, feature).
Is there any solutions?

**Comment by laszukdawid** [comment]
Hi @Waterkin , sorry for delay. As you mentioned, this PyEMD version is for univariate time series. That's mainly because it's difficult to formulate extremum in multivariate time series and also there isn't consensus what the envelop would mean. For own research I didn't need multivariate and didn't make any attempts. Feel free, and I'd really appreciate, to contribute if you can though :)
