### ISSUE TITLE
Problem with importing PyEMD

### ISSUE THREAD

**Issue by mcagrialtindal** [laszukdawid/PyEMD#154]
**Problem with importing PyEMD**
In order to run the package, I have tried the following steps:

1. pip install EMD-signal

2. In the python notebook with the same environment that I installed EMD-signal;
from PyEMD import EMD

When i try to import the package, I got the following error

ModuleNotFoundError: No module named 'PyEMD'

I have also tried to clone using,

git clone https://github.com/laszukdawid/PyEMD

and, 

python setup.py install

but looks like there is no setup.py file, and i was not able to solve the problem trying none of above methods. I use python 3.9.18. I would appreciate it if you could help me.

Best regards,

Mehmet

**Comment by alaudans** [comment]
I'm having the same issue. I'm on a new windows pc and trying to run code which was perfectly fine before but nothing I try will allow from PyEMD to be recognized.

**Comment by Luchauncy** [comment]
i have the same problems

**Comment by laszukdawid** [comment]
Please check either the README, or one of the previous issues, or any guide on the internet. This issue doesn't seem to be related to PyEMD but rather your Python setup.

**Comment by krahnikblis** [comment]
if you accidentally did `pip install pyemd` (and ended up with unrelated 'earth movers distance' library), uninstalling that might not remove its directory in your Python environment's site-packages folder. Python is case-sensitive but Windows is not, so you would have a "pyemd" folder there, which will not work with `from PyEMD import ...`. since all the files in the library also import from `PyEMD`, just changing your import to `pyemd` also won't work... 

renaming the folder (within your Python's site-packages directory) from `pyemd` to `PyEMD` worked for me
