### ISSUE TITLE
emd for pytorch code ?

### ISSUE THREAD

**Issue by iganggang** [laszukdawid/PyEMD#161]
could it work in CUDA?
I want to make it as a layer in PatchTST(a time series forecasting model)
class emd():
    def __init__(self, ):
        super(emd, self).__init__()
        self.emd = emd()
    def forward(self, x):
        imf1, imf2 = emd(x)
    return imf1, imf2

**Comment by laszukdawid** [comment]
What do you mean by "could it work in CUDA"? It could. Whether it's going to be faster? Unlikely. There's very little parallelization in EMD. In case of large time series, it might be performant to compute extrema and envelopes but casting data to and from gpu would take significant amount of time. The bottleneck in performance is usually the large number of sifting necessary.

**Comment by iganggang** [comment]
Sorry for my poor English. "Could it work in CUDA" means that EMD(x): could x be a tensor(batch size, sequence length, channels). Could this function process tensor?

**Comment by laszukdawid** [comment]
EMD only works on time series. EMD wouldn't know which dimension in your tensor is time series therefore it should fail.

I don't think there's an easy solution to processing many signals at once. That's because the number of sifting iteration depends on the signal's shape and so some signals will take longer to process.
