### ISSUE TITLE
What is your shifting  terminating condition/criterion

### ISSUE THREAD

**Issue by huangzhaor** [laszukdawid/PyEMD#34]
Is it SD threshold,like"sd = np.sum((x1 - x2) ** 2) / np.sum(x1 ** 2)"？Or another shifting criterion?

**Comment by laszukdawid** [comment]
I can only suggest to take a look at the code. There are few conditions depending on the setting. For example, EMD has:
IMF check: https://github.com/laszukdawid/PyEMD/blob/master/PyEMD/EMD.py#L683
end condition: https://github.com/laszukdawid/PyEMD/blob/master/PyEMD/EMD.py#L652

**Comment by huangzhaor** [comment]
I find it.
 # Standard deviation test
        std = np.sum(((imf_new-imf_old)/imf_new)**2)
        if std < self.std_thr:
            self.logger.debug("Standard deviation -- PASSED")
            return True
But I may have different idea because your test is a normal "standard deviation" test.
And Huang's condition seems like "np.sum((imf_new - imf_old) ** 2) / np.sum(imf_old** 2)"".That being said,the sum operation precedes the square operation and the denominator is imf_old rather than 'imf_new'.I don't know if what I say is right. I'd like to  suggest you check it again.

**Comment by laszukdawid** [comment]
Just checked it. Some resources confirm the present version, but you are right that in the original paper, Huang has used `np.sum(imf_diff**2) / np.sum(imf_old)**2`. Although `imf_old` vs `imf_new` in the denominator shouldn't make a much difference (they're expected to be close eitherway, so imf_new ~= imf_old) but the problem is with numerator. This does require update. Thank you for the detailed check :)

The problem is that since many have already downloaded the package and are using it, I'm reluctant to breaking changes, i.e. simply replacing the check. Let me think on this a little bit. Most likely I'll add another check and one will chose which it wants to use.

**Comment by laszukdawid** [comment]
Recent commit (2ed49900e479039c1a78aa322943c7755098bdea) adds another test to the stopping criteria that's in agreement with the original metric.

**Comment by huangzhaor** [comment]
Thanks

**Comment by laszukdawid** [comment]
It will be considered by default so to include this you don't have to do anything. There are current'y three threshold values that are checked (see below). Please change any of them accordingly. If you only want the energy ratio to be considered then set up everything else to zero. For example,
```python
emd = EMD()
emd.energy_ratio_thr = 0.2
emd.std_thr = 0
emd.svar_thr = 0
```
