### ISSUE TITLE
The ‘residuum’ in CEEMDAN and the decomposition is unstable

### ISSUE THREAD

**Issue by KrisLeezz** [laszukdawid/PyEMD#42]
Hello,  I am coming again.  I try the CEEMDAN() and found some problem.
There may be an error about the residuum in the `ceemdan()`. In my test, the `residuum` was strange.  
This is the result:
![image](https://user-images.githubusercontent.com/34668028/53335542-af164400-3936-11e9-9e76-212b65bd2888.png)
CEEMDAN can reconstruct the signal exactly. So, I checked the code.
The signal `S` is scaled `S[:] = S/scale_s`. The residuum is `S-np.sum(C_IMFs, axis=0)`. `S` has been changed. I passed the parameter `S` to the function `ceemdan()`, and I think the value of `S` shouldn't be changed. I'm not proficient in programming, this thought maybe wrong.

Another thing is that the decomposition results are unstable. I fixed the `S`. Except this, I did nothing about codes. This is the second result with he same data S:
![image](https://user-images.githubusercontent.com/34668028/53335695-1af8ac80-3937-11e9-9e5a-68c9df3a97dc.png)
This is the third result:
![image](https://user-images.githubusercontent.com/34668028/53335742-411e4c80-3937-11e9-852c-1a11ae6880f8.png)

Why is it?

**Comment by BlockWaving** [comment]
This looks like the distorting caused by 'end effects' of EMD method.  There are numerous academic paper discussed how to mitigate this problem.  Here is link to one such paper that gives thorough explanation as well a possible solution to the problem:
https://web.nmsu.edu/~spsandov/papers/GlobalSIP2018_Mitigate_End_Effects.pdf

**Comment by laszukdawid** [comment]
Hey both, apologies for the delay.

Thanks @KrisLeezz for sharing your results. There are plenty of caveats to EMD-related methods. The main one that will affect any results is that there is no "ideal" spline technique. If you are using the default setting for *EMD* then you are most likely using the Cubic spline. This is not only slow, as it requires transforming a matrix with as many rows are there are extrema, but it also tends to overshoot (sudden value jumps) to make smooth transition down-the-line. Having many of these overshoots in "weird" spots over many iterations will create a component that is not there. (At least from traditional, since-focused human point of view.) From my experience, these "weird spots" occure more often when the noise-to-signal ratio is large; when on short time-span minimum and maximum of similar values are followed by another extremum of significantly different value

Given that your signals are very noisy it this might happen often. Over few years of research I wasn't able to confirm EMD's "magical" properties to robustly handle noise.

Referring to you commend about the stability. CEEMDAN, same as EEMD, is intrinsically unstable. Its premise is that on a infinite ensemble (in practise "sufficiently large") of white noise assisted replicas the decomposition set will converge. Unless you want to fix pseudo-randomness each CEEMDAN execution will create a different component set. Hopefully, these component sets will be similar enough and sufficient for the need but if you see them being different I'd suggest increasing the number of performed iterations.

What I find interesting from your graphs is that the "original" signal has rather low amplitude compared to produced components. Could you confirm where are you getting this from? If that's on my side then it definitely needs fixing. 

In the last of your graphs the residue is mainly composed of the machine epsilon noise. In practise, consider this as a 0-component ;-)

**Comment by KrisLeezz** [comment]
Thanks for your help. I need to think more serious about this method.
The strange display of results is may be caused by the codes. Line 172 in CEEMD.py, the `S` is scaled by `scale_s` and the value of S is changed. The changed `S` is continued to be used to calculate residuum. I think this is the cause of 'low amplitude original signal'.
