### ISSUE TITLE
problem about  EEMD.py

### ISSUE THREAD

**Issue by sxinyuhoo** [laszukdawid/PyEMD#49]
Hi, when i am runnning EEMD.py (based on jupyter notebook , WIn10) as provided example, it occurs on an error, would you give some advice? Here  is the error: 
 \Anaconda3\envs\tensorflow\lib\site-packages\PyEMD\EEMD.py in eemd(self, S, T, max_imf)
    164         if T is None: T = np.arange(len(S), dtype=S.dtype)
    165 
--> 166         scale = self.noise_width * np.abs(np.max(S)-np.min(S))
    167         self._S = S
    168         self._T = T

AttributeError: 'numpy.ndarray' object has no attribute 'noise_width'

**Comment by laszukdawid** [comment]
Hey,
This is weird and I'm unable to reproduce this. Would you mind sharing a small code that creates the problem?

**Comment by sxinyuhoo** [comment]
Ok, here is the code: 

from PyEMD import EEMD
import numpy as np
import pylab as plt
t = np.linspace(0, 1, 200)
sin = lambda x, p: np.sin(2 * np.pi * x * t + p)
S = 3 * sin(18, 0.2) * (t - 0.2)**2
S += 5 * sin(11, 2.7)
S += 3 * sin(14, 1.6)
S += 1 * np.sin(4 * 2 * np.pi * (t - 0.8)**2)
S += t**2.1 - t
emd = EEMD.EEMD.emd
emd.extrema_detection = 'parabol'
eIMFs = EEMD.EEMD.eemd(S, t)
nIMFs = eIMFs.shape[0]

PS: I have to use **EEMD.EEMD.eemd(S, t)** rather than your method **EEMD()**, because it will report an error like **'module' object is not callable**

**Comment by laszukdawid** [comment]
That error is the problem :) notice that in the example (https://github.com/laszukdawid/PyEMD/blob/master/README.md) there's
`eemd = EEMD()` (brackets). They're required to instantiate the object. By skipping the you are directly evoking `eemd` method for which you are passing numoy array as the first argument.

Try:
```python
from PyEMD import EEMD
eemd = EEMD()
eemd.emd.extrema_detection = "parabol"
eIMFs = eemd(S, t)
```

**Comment by sxinyuhoo** [comment]
I also think it's the problem and have tried it following your advice, but it did not work.
When I directly use **eemd = EEMD()** or **eemd = EEMD.EEMD()**, it always occurs  **'module' object is not callable** . 
By the way, when I run EMD.py and try **emd = EMD()**, it occurs **'module' object is not callable**, while **emd = EMD.EMD()** works.

**Comment by laszukdawid** [comment]
Since you're running this from the Jupyter I guessing that there are some lingering from previous initiations, or something else is overriding the `*EMD` namespace. Can you restart the kernel and run these lines? Also, if you're having problems then try plainly in the interpreter without Jupyter/IPython.

Example lines:
```python
import numpy as np
from PyEMD import EEMD
eemd = EEMD()
t = np.arange(100)
S = eemd(np.sin(t*0.02))
eIMFs = eemd(S, t)
```

**Comment by sxinyuhoo** [comment]
I switch to PyCharm to run above code and the result is same.
Here is the detail:
```
from PyEMD import EEMD as ED
from numpy import np
```
When I then try `eemd = EEMD()`  or `eemd = ED()` or `eemd = ED.EEMD()`, it report **name 'EEMD' is not defined** , **'module' object is not callable**, **'module' object is not callable** respectively, but `eemd = ED.EEMD` without report.

 I guess it just can't instantiate the object.

**Comment by laszukdawid** [comment]
Apologies @sxinyuhoo but it looks like it's a problem with installation or usage in interpreter. Not sure how to help you since I'm unable to see exactly what's the configuration or what exact scripts you are running.

What I might suggest to try out is to delete PyEMD, create a new clean environment and install PyEMD there. To eliminate all potential side issues I'd suggest installing only PyEMD and try one by one adding other dependencies.
