### ISSUE TITLE
generalized zero crossing

### ISSUE THREAD

**Issue by wunderbarr** [laszukdawid/PyEMD#52]
Hello,
I would like to retrieve IMF frequencies. And I found this method [generalized zero crossing(GZC)](https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20080008712.pdf) is used in some paper. Is it possible to implement this function in your library? :)

**Comment by laszukdawid** [comment]
Hey,

Unfortunately, at the moment I'm rather busy with other projects and can't say when I'll be able to do something more on PyEMD. Not sure if I understand the motivation behind the GZC, seems like another "because it worked for us" algorithm, but I'm interested to see whether it'd be an interesting feature channel.

Will let you know next week (I'm on holidays now) whether I'll try to do this.

Nevertheless, thanks for the suggestion! It's always great to see what people are coming up with :-)

**Comment by laszukdawid** [comment]
Hey, I decided not to implement this since the document looks like a patent and I'm not sure what's the implication on the library. The last thing I want anyone is to be unable to use the PyEMD because some part of it is patented.
