### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Yuannezhao** [laszukdawid/PyEMD#55]
HI, I try to install in root using pip install. But it shows an error:
ERROR: Cannot uninstall 'scipy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

It is necessary to uninstall 'scipy'?

**Comment by laszukdawid** [comment]
Hi, this an independent issue from the PyEMD so you might find some help on the internet/StackOverflow.

PyEMD requires Scipy to run so uninstalling isn't required. What i'm thinking is that you have an old Scipy version and for the PyEMD we [require](https://github.com/laszukdawid/PyEMD/blob/master/requirements.txt) at least version 0.19. It might be that an upgrade from whatever version you have at the root to the newer one requires uninstalling and installing again. Please check that by upgrading Scipy through running:
```$ pip install scipy --upgrade```

**Comment by Yuannezhao** [comment]
Hi, thanks for your reply!  I have solved this problem. It is indeed some
problem in my local environment. Now it is installed successfully!

I hope use the EMD2d to decompose 2-D image. But I notice there are two
classes, EMD2D and BEMD for decomposing image. The BEMD is based on
[Nunes,2003] 'Image analysis by bidimensional empirical mode
decomposition'. Image and Vision Computing”, Elsevier, 2003, 21 (12),
pp.1019-1026. Which paper is EMD2D based on? Also what is the difference
between them?  It is a very interesting method to analyze the image. Do you
think it is possible to extracte different features at different scales
from an image? Here I put an example. Many thanks for your response in
advance.

[image: Capture du 2019-06-11 13-06-00.png]

Kind regards,

Yuan




Dawid Laszuk <notifications@github.com> 于2019年6月7日周五 下午7:34写道：

**Comment by laszukdawid** [comment]
In the future, let's please keep *issues* with a single question/issue, so I'd advice next questions on EMD2D/BEMD to be in a separate issue.

To answer your questions: the EMD2D is based on what makes sense to me. It [searches for extrema](https://github.com/laszukdawid/PyEMD/blob/master/PyEMD/EMD2d.py#L165) in images through erosion and spans 2d splines as images. In my opinion it showed nice results for certain classes of "images" but, unfortunately, it's difficult to make it work in general. For this reason, both **EMD2D and BEMD are not supported and they should be treated as is**. Feel free to contribute and make it better, so that we can support it in future :)

Since the original issue is resolved I'm closing the topic. Feel free to open new ones with questions.
